  // import { Geist, Geist_Mono } from "next/font/google";
  // import "./globals.css";
  // import { Toaster } from "react-hot-toast";
  // import AuthProvider from "@/components/AuthProvider";

  // const geistSans = Geist({
  //   variable: "--font-geist-sans",
  //   subsets: ["latin"],
  // });

  // const geistMono = Geist_Mono({
  //   variable: "--font-geist-mono",
  //   subsets: ["latin"],
  // });

  // export const metadata = {
  //   title: "Create Next App",
  //   description: "Generated by create next app",
  // };

  // export default function RootLayout({ children }) {
  //   return (
  //     <html lang="en">
  //       <body
  //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
  //       >
  //         <Toaster
  //           position="top-center"
  //           toastOptions={{
  //             duration: 3000,
  //           }}
  //         />
      
  //         {children}

  //         <AuthProvider/>
        
  //       </body>
  //     </html>
  //   );
  // }


// import { Geist, Geist_Mono } from "next/font/google";
// import Script from "next/script";
// import "./globals.css";
// import { Toaster } from "react-hot-toast";
// import AuthProvider from "@/components/AuthProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <head>
//         {/* ✅ Razorpay SDK */}
//         <Script
//           src="https://checkout.razorpay.com/v1/checkout.js"
//           strategy="afterInteractive"
//         />
//       </head>

//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {/* ✅ Toast */}
//         <Toaster
//           position="top-center"
//           toastOptions={{
//             duration: 3000,
//           }}
//         />

//         {/* ✅ Auth Initialization */}
//         <AuthProvider />

//         {/* ✅ App Content */}
//         {children}
//       </body>
//     </html>
//   );
// }

import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/components/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ Razorpay SDK */}
        <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="afterInteractive"
        />

        {/* ✅ Toast */}
        <Toaster
          position="top-center"
          toastOptions={{
            duration: 3000,
          }}
        />

        {/* ✅ Auth Initialization */}
        <AuthProvider />

        {/* ✅ App Content */}
        {children}
      </body>
    </html>
  );
}