

import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/components/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* #region agent log */}
        {typeof window !== "undefined" &&
          fetch(
            "http://127.0.0.1:7242/ingest/0119ffd1-4c35-47dc-b064-ec4d389574d6",
            {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({
                runId: "pre-fix",
                hypothesisId: "E",
                location: "src/app/layout.js:RootLayout",
                message: "RootLayout render (client)",
                data: {},
                timestamp: Date.now(),
              }),
            }
          ).catch(() => {})}
        {/* #endregion */}

        {/* ✅ Razorpay SDK */}
        <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="afterInteractive"
        />

        {/* ✅ Toast */}
        <Toaster
          position="top-center"
          toastOptions={{
            duration: 3000,
          }}
        />

        {/* ✅ Auth Initialization */}
        <AuthProvider />

        {/* ✅ App Content */}
        {children}
      </body>
    </html>
  );
}